### ISSUE TITLE
Does not build using python3.4

### ISSUE THREAD

**Issue by McNoggins** [luispedro/imread#17]
I'm trying to build the imread module using python3.4. I was able to build it using python2 (submitted to the Arch User repository here https://aur.archlinux.org/packages/python2-imread/). However using 3.4 I get the following errors:

---

building 'imread._imread' extension
compiling C++ sources
C compiler: g++ -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC

compile options: '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DPY_ARRAY_UNIQUE_SYMBOL=MahotasImread_PyArray_API_Symbol -I/usr/local/include -I/usr/lib/python3.4/site-packages/numpy/core/include -I/usr/include/python3.4m -c'
g++: imread/_imread.cpp
In file included from /usr/include/python3.4m/pyatomic.h:8:0,
                 from /usr/include/python3.4m/Python.h:53,
                 from imread/lib/numpy.h:11,
                 from imread/_imread.cpp:23:
/usr/include/python3.4m/dynamic_annotations.h:472:3: error: template with C linkage
   template <class T>
   ^
In file included from /usr/include/python3.4m/pyatomic.h:8:0,
                 from /usr/include/python3.4m/Python.h:53,
                 from imread/lib/numpy.h:11,
                 from imread/_imread.cpp:23:
/usr/include/python3.4m/dynamic_annotations.h:472:3: error: template with C linkage
   template <class T>
   ^
## error: Command "g++ -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DPY_ARRAY_UNIQUE_SYMBOL=MahotasImread_PyArray_API_Symbol -I/usr/local/include -I/usr/lib/python3.4/site-packages/numpy/core/include -I/usr/include/python3.4m -c imread/_imread.cpp -o build/temp.linux-x86_64-3.4/imread/_imread.o" failed with exit status 1

Any idea where the error may come from? I hope this helps.
